baseURL = 'https://github.com/cwyang/hugo-simple'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Tags'
pageRef = '/tags/'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
