# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: cwyang's blog
#email: cwyang
description: > # this means to ignore newlines until "baseurl:"
  short essays
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cwyang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cwyang
github_username:  cwyang

paginate:	10
timezone: "Asia/Seoul"

#blog logo
logo: "/assets/images/logo.jpg"
cover: "/assets/images/background_image.jpg"
name: 'cwyang'
author: '양철웅(Chul-Woong Yang)'
author_image: "/assets/images/author.jpg"

twitter_handle: '@cwyang'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
social:
  - icon:	facebook
    url:	https://facebook.com/cwyang72
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
  - icon:	twitter
    url:	https://twitter.com/cwyang
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
