# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-toc

# Site settings
title: 양철웅의 DX 이야기
description: > # this means to ignore newlines until "email:"
  short essays on DX, cyber security, and cloud
url: "http://cwyang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cwyang
github_username:  cwyang
logo: "/assets/images/cwyang2016.jpg"
cover: "/assets/images/background_image.jpg"
name: 'cwyang'
author: 양철웅
author_bio: Chul-Woong Yang
author_image: "/assets/images/author.jpg"
google_analytics: UA-6183151-15
twitter_handle: '@cwyang'

paginate:	15

permalink: /:year/:month/:day/:title.html

timezone: "Asia/Seoul"

# tracking & ad code
fb_app_id: "596017104565491"
google_analytics_id: "UA-6183151-15"
naver_site_verification: "cec40b2338ce973c5b5588326daed5c126a0c415"

#################################

social:
  - icon:	facebook
    url:	https://facebook.com/cwyang89
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
  - icon:	twitter
    url:	https://twitter.com/cwyang
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
defaults:
  - scope:
            path: "docs/**"
    values:
            sitemap: false
  - scope:
            path: "play/**"
    values:
            sitemap: false
  - scope:
            path: "[g|n]*.html"
    values:
            sitemap: false
exclude:
  - play/
  - vendor/
  - docs/
  - Gemfile*
  - gulpfile.js
  - package.json
  - run
