# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-toc

# Site settings
title: cwyang's blog
description: > # this means to ignore newlines until "email:"
  short essays
url: "http://cwyang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cwyang
github_username:  cwyang
logo: "/assets/images/logo.jpg"
cover: "/assets/images/background_image.jpg"
name: 'cwyang'
author: 양철웅
author_bio: Chul-Woong Yang
author_image: "/assets/images/author.jpg"
google_analytics: UA-6183151-15
twitter_handle: '@cwyang'

paginate:	15

permalink: /:year/:month/:day/:title.html

timezone: "Asia/Seoul"


#################################

social:
  - icon:	facebook
    url:	https://facebook.com/cwyang72
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
  - icon:	twitter
    url:	https://twitter.com/cwyang
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
